theme = "my_tokyonight"

[editor]
line-number = "relative"
scrolloff = 8
cursorline = true
bufferline = "multiple"
color-modes = true
popup-border = "all"

auto-format = true
insert-final-newline = true
trim-trailing-whitespace = true
trim-final-newlines = false

end-of-line-diagnostics = "hint"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "version-control",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.gutters.line-numbers]
min-width = 2

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = "↪ "

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
K = "hover"

[keys.normal.space.l]
d = "goto_definition"
r = "goto_reference"
i = "goto_implementation"
t = "goto_type_definition"
R = "rename_symbol"
a = "code_action"
h = ":toggle-option lsp.display-inlay-hints"
s = "signature_help"

[keys.normal."]"]
d = "goto_next_diag"
D = "goto_last_diag"

[keys.normal."["]
d = "goto_prev_diag"
D = "goto_first_diag"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
